### PR TITLE
Upgrade to Bevy 0.12

### PR DESCRIPTION
**Pull request by rparrett**
This is incomplete. Still working through shader migrations. But the project compiles.

I will pick this up again later if nobody else beats me to it. (Other users: feel free to make a PR to the `bevy-0.12` branch of my fork)

### CODE REVIEW

**Comment by rparrett** [comment]
Okay, this is in a generally working state now, but I have a feeling that what I did in the shaders was a bit of a hack job. I really have very little idea of what is going on in there.

image

**Comment by rparrett** [comment]
Also, there are a number of warnings about deprecations that should be cleaned up.

**Comment by Game4all** [comment]
I haven't looked much into the code, but by running this branch it seems shadows are gone :( (I'm not up to date with bevy versions so i'm not sure what may be happening).

**Comment by Game4all** [comment]
Here's a screenshot of master
image

**Review by Game4all — APPROVED** [review]
Lgtm! Please add mention of your migration work on the README for credit if you feel like it

**Comment by rparrett** [comment]
Will do. We do still need to wait on [bevy_atmostphere](https://github.com/JonahPlusPlus/bevy_atmosphere/pull/61) -- can't publish with a git dependency.

**Comment by Game4all** [comment]
Thanks!

**Pull request merged**
