### PR TITLE
change rendering engine to use PBR with standard pipelines

### PR DESCRIPTION
**Pull request by meyerzinn**
… shadows!

(should probably investigate meshing water / translucent objects separately?)

Screenshot 2023-05-01 at 20 07 57

### CODE REVIEW

**Comment by meyerzinn** [comment]
This incurs an FPS penalty which brings it to ~50fps on my M1 MacBook Air. Personally, I think the shadows are substantially nice enough to make the performance hit worth it -- especially once Bevy has SSAO.

**Comment by meyerzinn** [comment]
Probably need to tune the cascading shadow maps a bit. Note the jagged edges.

Screenshot 2023-05-01 at 20 12 01

**Comment by Game4all** [comment]
Liquids / translucent voxels should probably be meshed separately but I find allocating a whole mesh for just translucents voxels a bit much, maybe merge them in a single mesh and use draw command magic to only draw the "opaque part" of the mesh and then draw the "transparent part" of it.

**Review by Game4all — APPROVED** [review]
Looking fine

**Comment by Game4all** [comment]
Can this be merged as is or does it need further tweaking ?

**Comment by meyerzinn** [comment]
My initial attempts to tune the settings hasn't yielded any improvement to the shadow quality, so I'm happy to merge as-is and just let the engine improvements carry it.

**Comment by meyerzinn** [comment]
Re: liquids & translucent voxels, there is the concern of them having different orderings (need to sort opaque things front-to-back and translucent things back-to-front before drawing). I suspect having separate materials/meshes for them will ultimately be easier within the existing framework (they could be two children entities of the chunk, for instance) but I haven't given it much actual thought yet.

**Review by Game4all — APPROVED** [review]
lgtm

**Pull request merged**
